name: adsdb

channels:
  - conda-forge

dependencies:
  - python=3.9.*
  - numpy
  - matplotlib
  - pandas
  - seaborn
  - psycopg2
  - sqlalchemy
  - scipy
  - pandas-profiling
  - scikit-learn
  - plotly
  - ipykernel
  - pip

  - pip:
    - wbdata
    - pyenchant
